### ISSUE TITLE
1.17.1 Server problems

### ISSUE THREAD

**Issue by DMSledge** [B1n-ry/Youre-in-grave-danger#1]
On a 1.17.1 server the graves are erasing current inventory as well as not disappearing when emptied.

**Comment by B1n-ry** [comment]
Did the grave give your stuff back? Can you provide any logs?

**Comment by DMSledge** [comment]
The grave did restore items over top the existing inventory.
`[12:39:15]
[FATAL] Error executing task on Server
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "modInventories" is null
at com.b1n4ry.yigd.block.GraveBlock.RetrieveItems(GraveBlock.java:237) ~[youre-in-grave-danger-1.1.1.jar:?]
at com.b1n4ry.yigd.block.GraveBlock.method_9534(GraveBlock.java:84) ~[youre-in-grave-danger-1.1.1.jar:?]
at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:938) ~[intermediary-server.jar:?]
at net.minecraft.class_3225.method_14262(class_3225.java:327) ~[intermediary-server.jar:?]
at net.minecraft.class_3244.method_12046(class_3244.java:1050) ~[intermediary-server.jar:?]
at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[intermediary-server.jar:?]
at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[intermediary-server.jar:?]
at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by B1n-ry** [comment]
Thanks I think I located and fixed the problem. Please let me know if you have any other problem, or this somehow reoccur. I've pushed a new update to both curseforge and modrinth that should fix this ~~and adds some other neat features~~

**Comment by DMSledge** [comment]
Looks to be working so far. :)
