### ISSUE TITLE
inventory wiped on grave interact

### ISSUE THREAD

**Issue by SilverStr3ak** [B1n-ry/Youre-in-grave-danger#181]
any time i interact with the gravestone my inventory is wiped and i gain experience. the experience can grow to large amounts by holding right click. Here is the log from my launcher. Im playing in the prominence II modpack.

at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[15/09/2024 11:06:34 AM] 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[15/09/2024 11:06:34 AM] 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[15/09/2024 11:06:34 AM] 	at java.base/java.util.Objects.checkIndex(Objects.java:361)
[15/09/2024 11:06:34 AM] 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
[15/09/2024 11:06:34 AM] 	at net.minecraft.class_2371.get(class_2371.java:47)
[15/09/2024 11:06:34 AM] 	at com.b1n_ry.yigd.compat.TrinketsCompat$TrinketsCompatComponent.merge(TrinketsCompat.java:202)
[15/09/2024 11:06:34 AM] 	at com.b1n_ry.yigd.components.InventoryComponent.merge(InventoryComponent.java:337)
[15/09/2024 11:06:34 AM] 	at com.b1n_ry.yigd.components.GraveComponent.applyToPlayer(GraveComponent.java:592)
[15/09/2024 11:06:34 AM] 	at com.b1n_ry.yigd.packets.ServerPacketHandler.lambda$registerReceivers$6(ServerPacketHandler.java:83)
[15/09/2024 11:06:34 AM] 	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
[15/09/2024 11:06:34 AM] 	at com.b1n_ry.yigd.packets.ServerPacketHandler.lambda$registerReceivers$8(ServerPacketHandler.java:82)
[15/09/2024 11:06:34 AM] 	at net.minecraft.class_3738.run(class_3738.java:18)
[15/09/2024 11:06:34 AM] 	at net.minecraft.class_1255.method_18859(class_1255.java:156)
[15/09/2024 11:06:34 AM] 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[15/09/2024 11:06:34 AM] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
[15/09/2024 11:06:34 AM] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[15/09/2024 11:06:34 AM] 	at net.minecraft.class_1255.method_16075(class_1255.java:130)
[15/09/2024 11:06:34 AM] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
[15/09/2024 11:06:34 AM] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
[15/09/2024 11:06:34 AM] 	at net.minecraft.class_1255.method_5383(class_1255.java:115)
[15/09/2024 11:06:34 AM] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
[15/09/2024 11:06:34 AM] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
[15/09/2024 11:06:34 AM] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[15/09/2024 11:06:34 AM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[15/09/2024 11:06:34 AM] [Server thread/FATAL] Error executing task on Server

**Comment by B1n-ry** [comment]
What mod version are you using? Because this exact error message shouldn't really be possible with the latest version of the mod (given where the error is located, and from what line its caused)

**Comment by SilverStr3ak** [comment]
i updated the mod i had an older version. ty
