### ISSUE TITLE
Compat issue with Travelers Backpack after theyr Update

### ISSUE THREAD

**Issue by suerion** [B1n-ry/Youre-in-grave-danger#196]
Hey, i had added the issue on the Travelers Backpack side.

i think it is only an rework from some namespaces, to fix this

https://github.com/Tiviacz1337/Travelers-Backpack/issues/1095

**Comment by suerion** [comment]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.21.1 on 0.16.9
Minecraft 1.21.1
You're in Grave Danger 2.4.11
[1.21.1] Traveler's Backpack 10.1.4

An a lot of more

1. Describe the bug 

Crash on Server Startup with YIGD
```
[22:16:41 ERROR] [main]: [Main] Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'yigd' at 'com.b1n_ry.yigd.Yigd'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoSuchFieldError: Class com.tiviacz.travelersbackpack.config.TravelersBackpackConfigData$BackpackSettings does not have member field 'boolean accessoriesIntegration'
        at knot/com.b1n_ry.yigd.compat.TravelersBackpackCompat.isAccessoriesIntegrationEnabled(TravelersBackpackCompat.java:22) ~[youre-in-grave-danger-fabric-2.4.11.jar:?]
        at knot/com.b1n_ry.yigd.compat.InvModCompat.reloadModCompat(InvModCompat.java:31) ~[youre-in-grave-danger-fabric-2.4.11.jar:?]
        at knot/com.b1n_ry.yigd.Yigd.onInitialize(Yigd.java:83) ~[youre-in-grave-danger-fabric-2.4.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
```

2. Write steps to reproduce the bug

Add newest update 10.1.4

3. What is expected behaviour 

Server starts without issues.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Hello, Backpack component has been reworked and is no longer used if trinkets/accessories integration is enabled. You can Remove checks for this config option. Also backpack custom drop is supressed if trinkets/accessories enabled, so it drops by default from trinkets/accessories inventory. 

I'd suggest for you to just check if TravelersBackpack#enableIntegration && ComponentUtils#isWearingBackpack and execute grave code if it returns true - it means trinkets/accessories not installed (or installed but config option disabled) and player is wearing backpack

**Comment by Alejandrojcv4** [comment]
I did start the server without the yigd, stop, add it back, and start again, that solved my problem. Also doing what Tiviac said, dissabling enableTravelersBackpackCompat and enableTrinketsCompat is enough for it to work without crashing.

**Comment by suerion** [comment]
> I did start the server without the yigd, stop, add it back, and start again, that solved my problem. Also doing what Tiviac said, dissabling enableTravelersBackpackCompat and enableTrinketsCompat is enough for it to work without crashing.

Yeah, this is a workaround, but fix not an crash

**Comment by B1n-ry** [comment]
Sorry I realized I never replied here. A new update with a fix should be released in just a few days for neoforge. I can't seem to get 10.1.4 loaded in my development environment on fabric with the correct mappings for some reason though, so that might prove harder to fix. I'll try though

**Comment by suerion** [comment]
@B1n-ry you could look here for the right mappings -> https://github.com/Skidamek/AutoModpack

Skidamek has the gradle always up to date

**Comment by B1n-ry** [comment]
I'm pretty confident that my mappings and gradle are up to date, however with the latest 2 fabric versions of travelers backpack, when trying to use them in my development environment, either loom will fail to remap from mojmap to yarn, or I will get "unfixable exception", which if I understand it correctly comes from mappings overlapping or something.
I have to admit gradle is not my strong suit though, so I'm probably doing something wrong

**Comment by suerion** [comment]
Ah okey, sorry, thats not my intention, had thougt i could help, if loom or some things are not getting right.

**Comment by Tiviacz1337** [comment]
I use parchment mappings on fabric too if it changes something

**Comment by B1n-ry** [comment]
Alright I remapped to mojmap, and then I was allowed to fix it. 
Fixed as of YiGD 2.4.12 for fabric, or 2.0.8 for neoforge (1.21)
