### ISSUE TITLE
Parsing error loading recipe yigd:death_scroll

### ISSUE THREAD

**Issue by TheAyes** [B1n-ry/Youre-in-grave-danger#43]
**Describe the bug**
Seems like there's supposed to be an item? No crashes occurring, just wanted to let you know that I get this error message in log.

**Expected behavior**
There might be an item that couldn't be found.

**Desktop (please complete the following information):**
 - OS: Win11
 - Minecraft Version: 1.18.2
 - Version: 1.3.2
 - 
**Log**
```
[14:16:58] [Render thread/ERROR]: Parsing error loading recipe yigd:death_scroll
com.google.gson.JsonSyntaxException: Unknown item 'yigd:death_scroll'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:273) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:260) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_40183(class_310.java:2123) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1972) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29607(class_310.java:1941) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:286) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:230) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1150) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.16.0-beta.16.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.16.0-beta.16.jar:?]
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28) [quilt-loader-0.16.0-beta.16.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23) [quilt-loader-0.16.0-beta.16.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by B1n-ry** [comment]
This is actually expected to happen for most people. There is a configurable item in the mod, which I've added a recipe to. The recipe will always try to load since it's vanilla minecraft datagen, but in most cases the item is not initialized since not everyone wants these configurable features.
Thank you for sending this in anyway! Even though this is not an issue, there could be something similar you would happen to find, and in that case getting that info would help me fixing potential problems and such

**Comment by mattthw** [comment]
You could update the mod to not load it if it is not configured? Most people want to avoid red herring errors in their logs
