### ISSUE TITLE
Crashes if trying to load with a server

### ISSUE THREAD

**Issue by TheAyes** [B1n-ry/Youre-in-grave-danger#48]
**Describe the bug**
[08:31:55] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'yigd'!
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.16.1-beta.3.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.launch.knot.KnotHelper.launchServer(KnotHelper.java:32) [quilt-loader-0.16.1-beta.3.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:23) [quilt-loader-0.16.1-beta.3.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:62) [quilt-loader-0.16.1-beta.3.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at com.b1n_ry.yigd.Yigd.onInitialize(Yigd.java:210) ~[youre-in-grave-danger-1.3.2.jar:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:32) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:58) ~[quilt-loader-0.16.1-beta.3.jar:?]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.b1n_ry.yigd.Yigd.onInitialize(Yigd.java:210) ~[youre-in-grave-danger-1.3.2.jar:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:32) ~[quilt-loader-0.16.1-beta.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:58) ~[quilt-loader-0.16.1-beta.3.jar:?]
        ... 13 more

**Expected behavior**
A normal server start.

**Desktop:**
 - OS: Windows
 - Minecraft Version: 1.16.2
 - Version: 1.3.2

**Additional context**
I'm using the quilt server jar. Not sure if it only applies to that.

**Comment by TheAyes** [comment]
Update: same error on 1.3.5

**Comment by TheAyes** [comment]
Update: Also happens on fabric server jar.

**Comment by B1n-ry** [comment]
I just want to make sure when using 1.3.5 you are getting the same crash, and not the one in #46? If it's the same I'll check on it but if not you can read what I told that guy and do the same you too

**Comment by TheAyes** [comment]
I've already tried it and yes it's the very same error as seen above.

**Comment by B1n-ry** [comment]
Ok great just wanted to make sure.
Also, I just noticed now, are you trying to run this version on a 1.16.2 server? Because if that's the cause of this issue then you'll justhave to try a 1.16.5 version of the mod. That version will not include as many features, but most of them will be there.
Anyway I strongly believe this is not the same error as you get in version 1.3.5, since I fixed this error in the 1.3.3 version. If you could send the crash report from version 1.3.5 that could help me further to find the problem (unless you're playing at 1.16.2, in which I'm pretty sure that won't help)

**Comment by TheAyes** [comment]
Might've been my typo sorry. I'm running 1.18.2 not 1.16
[latest.log](https://github.com/B1n-ry/Youre-in-grave-danger/files/8714364/latest.log)

**Comment by B1n-ry** [comment]
Thanks. This does very much look like #46 actually. If you want I can fix the config file for you, or you can try to check the wiki to fix for yourself or just delete the config file and recreate it as you want it

**Comment by TheAyes** [comment]
That's strange :o I could've sworn I tried deleting the config several times now. well either way it's working now thanks!
